### PR TITLE
Edit to README.md

### PR DESCRIPTION
**Pull request by ricemkira**
"...just a few thoughts about (how) to learn best using learn.co."...

### CODE REVIEW

**Comment by kiramrice** [comment]
Added the word "how"

**Comment by kiramrice** [comment]
"Before you get started, just a few thoughts about how to learn best using learn.co."

Not sure if this sentence is useful as it isn't followed by any particular stream of "thoughts".

**Comment by joshrowley** [comment]
Hey thanks for this @ricemkira

**Comment by joshrowley** [comment]
oh whoops sorry, this should be submitted to the main lab repo over here: https://github.com/learn-co-curriculum/welcome-to-learn-verified

**Pull request merged**
